export const medicationOptions = [
    {value: "Atorvastatin", label: "Atorvastatin"},
    {value: "Levothyroxine", label: "Levothyroxine"},
    {value: "Lisinopril", label: "Lisinopril"},
    {value: "Metformin", label: "Metformin"},
    {value: "Metoprolol", label: "Metoprolol"},
    {value: "Amlodipine", label: "Amlodipine"},
    {value: "Albuterol", label: "Albuterol"},
    {value: "Omeprazole", label: "Omeprazole"},
    {value: "Losartan", label: "Losartan"},
    {value: "Gabapentin", label: "Gabapentin"},
    {value: "Hydrochlorothiazide", label: "Hydrochlorothiazide"},
    {value: "Sertraline", label: "Sertraline"},
    {value: "Simvastatin", label: "Simvastatin"},
    {value: "Montelukast", label: "Montelukast"},
    {value: "Acetaminophen; Hydrocodone", label: "Acetaminophen; Hydrocodone"},
    {value: "Pantoprazole", label: "Pantoprazole"},
    {value: "Furosemide", label: "Furosemide"},
    {value: "Fluticasone", label: "Fluticasone"},
    {value: "Escitalopram", label: "Escitalopram"},
    {value: "Fluoxetine", label: "Fluoxetine"},
    {value: "Rosuvastatin", label: "Rosuvastatin"},
    {value: "Bupropion", label: "Bupropion"},
    {value: "Amoxicillin", label: "Amoxicillin"},
    {value: "Dextroamphetamine; Dextroamphetamine Saccharate; Amphetamine; Amphetamine Aspartate", label: "Dextroamphetamine; Dextroamphetamine Saccharate; Amphetamine; Amphetamine Aspartate"},
    {value: "Trazodone", label: "Trazodone"},
    {value: "Duloxetine", label: "Duloxetine"},
    {value: "Prednisone", label: "Prednisone"},
    {value: "Tamsulosin", label: "Tamsulosin"},
    {value: "Ibuprofen", label: "Ibuprofen"},
    {value: "Citalopram", label: "Citalopram"},
    {value: "Meloxicam", label: "Meloxicam"},
    {value: "Pravastatin", label: "Pravastatin"},
    {value: "Carvedilol", label: "Carvedilol"},
    {value: "Potassium", label: "Potassium"},
    {value: "Tramadol", label: "Tramadol"},
    {value: "Clopidogrel", label: "Clopidogrel"},
    {value: "Insulin Glargine", label: "Insulin Glargine"},
    {value: "Aspirin", label: "Aspirin"},
    {value: "Atenolol", label: "Atenolol"},
    {value: "Venlafaxine", label: "Venlafaxine"},
    {value: "Alprazolam", label: "Alprazolam"},
    {value: "Ethinyl Estradiol; Norethindrone", label: "Ethinyl Estradiol; Norethindrone"},
    {value: "Allopurinol", label: "Allopurinol"},
    {value: "Hydrochlorothiazide; Lisinopril", label: "Hydrochlorothiazide; Lisinopril"},
    {value: "Cyclobenzaprine", label: "Cyclobenzaprine"},
    {value: "Clonazepam", label: "Clonazepam"},
    {value: "Zolpidem", label: "Zolpidem"},
    {value: "Azithromycin", label: "Azithromycin"},
    {value: "Oxycodone", label: "Oxycodone"},
    {value: "Warfarin", label: "Warfarin"},
    {value: "Methylphenidate", label: "Methylphenidate"},
    {value: "Apixaban", label: "Apixaban"},
    {value: "Ranitidine", label: "Ranitidine"},
    {value: "Glipizide", label: "Glipizide"},
    {value: "Ergocalciferol", label: "Ergocalciferol"},
    {value: "Quetiapine", label: "Quetiapine"},
    {value: "Budesonide; Formoterol", label: "Budesonide; Formoterol"},
    {value: "Estradiol", label: "Estradiol"},
    {value: "Acetaminophen; Oxycodone", label: "Acetaminophen; Oxycodone"},
    {value: "Ondansetron", label: "Ondansetron"},
    {value: "Naproxen", label: "Naproxen"},
    {value: "Glimepiride", label: "Glimepiride"},
    {value: "Spironolactone", label: "Spironolactone"},
    {value: "Clonidine", label: "Clonidine"},
    {value: "Insulin Lispro", label: "Insulin Lispro"},
    {value: "Loratadine", label: "Loratadine"},
    {value: "Cetirizine", label: "Cetirizine"},
    {value: "Topiramate", label: "Topiramate"},
    {value: "Lorazepam", label: "Lorazepam"},
    {value: "Ethinyl Estradiol; Norgestimate", label: "Ethinyl Estradiol; Norgestimate"},
    {value: "Lamotrigine", label: "Lamotrigine"},
    {value: "Diltiazem", label: "Diltiazem"},
    {value: "Hydrochlorothiazide; Losartan", label: "Hydrochlorothiazide; Losartan"},
    {value: "Diclofenac", label: "Diclofenac"},
    {value: "Hydroxyzine", label: "Hydroxyzine"},
    {value: "Buspirone", label: "Buspirone"},
    {value: "Latanoprost", label: "Latanoprost"},
    {value: "Paroxetine", label: "Paroxetine"},
    {value: "Lisdexamfetamine", label: "Lisdexamfetamine"},
    {value: "Fluticasone; Salmeterol", label: "Fluticasone; Salmeterol"},
    {value: "Pregabalin", label: "Pregabalin"},
    {value: "Propranolol", label: "Propranolol"},
    {value: "Cephalexin", label: "Cephalexin"},
    {value: "Cholecalciferol", label: "Cholecalciferol"},
    {value: "Insulin Aspart", label: "Insulin Aspart"},
    {value: "Finasteride", label: "Finasteride"},
    {value: "Fenofibrate", label: "Fenofibrate"},
    {value: "Sitagliptin", label: "Sitagliptin"},
    {value: "Folic Acid", label: "Folic Acid"},
    {value: "Doxycycline", label: "Doxycycline"},
    {value: "Rivaroxaban", label: "Rivaroxaban"},
    {value: "Tizanidine", label: "Tizanidine"},
    {value: "Amoxicillin; Clavulanate", label: "Amoxicillin; Clavulanate"},
    {value: "Amitriptyline", label: "Amitriptyline"},
    {value: "Lovastatin", label: "Lovastatin"},
    {value: "Alendronate", label: "Alendronate"},
    {value: "Levetiracetam", label: "Levetiracetam"},
    {value: "Sumatriptan", label: "Sumatriptan"},
    {value: "Hydralazine", label: "Hydralazine"},
    {value: "Sulfamethoxazole; Trimethoprim", label: "Sulfamethoxazole; Trimethoprim"},
    {value: "Aripiprazole", label: "Aripiprazole"},
    {value: "Celecoxib", label: "Celecoxib"},
    {value: "Ferrous Sulfate", label: "Ferrous Sulfate"},
    {value: "Famotidine", label: "Famotidine"},
    {value: "Benzonatate", label: "Benzonatate"},
    {value: "Mirtazapine", label: "Mirtazapine"},
    {value: "Triamcinolone", label: "Triamcinolone"},
    {value: "Ezetimibe", label: "Ezetimibe"},
    {value: "Fluticasone; Vilanterol", label: "Fluticasone; Vilanterol"},
    {value: "Valacyclovir", label: "Valacyclovir"},
    {value: "Methotrexate", label: "Methotrexate"},
    {value: "Oxybutynin", label: "Oxybutynin"},
    {value: "Ciprofloxacin", label: "Ciprofloxacin"},
    {value: "Valproate", label: "Valproate"},
    {value: "Triamterene; Hydrochlorothiazide", label: "Triamterene; Hydrochlorothiazide"},
    {value: "Thyroid", label: "Thyroid"},
    {value: "Diazepam", label: "Diazepam"},
    {value: "Nifedipine", label: "Nifedipine"},
    {value: "Clindamycin", label: "Clindamycin"},
    {value: "Donepezil", label: "Donepezil"},
    {value: "Insulin Detemir", label: "Insulin Detemir"},
    {value: "Hydroxychloroquine", label: "Hydroxychloroquine"},
    {value: "Isosorbide", label: "Isosorbide"},
    {value: "Ethinyl Estradiol; Levonorgestrel", label: "Ethinyl Estradiol; Levonorgestrel"},
    {value: "Baclofen", label: "Baclofen"},
    {value: "Testosterone", label: "Testosterone"},
    {value: "Esomeprazole", label: "Esomeprazole"},
    {value: "Desogestrel; Ethinyl Estradiol", label: "Desogestrel; Ethinyl Estradiol"},
    {value: "Oseltamivir", label: "Oseltamivir"},
    {value: "Benazepril", label: "Benazepril"},
    {value: "Dexmethylphenidate", label: "Dexmethylphenidate"},
    {value: "Tiotropium", label: "Tiotropium"},
    {value: "Fluconazole", label: "Fluconazole"},
    {value: "Dulaglutide", label: "Dulaglutide"},
    {value: "Chlorthalidone", label: "Chlorthalidone"},
    {value: "Methocarbamol", label: "Methocarbamol"},
    {value: "Enalapril", label: "Enalapril"},
    {value: "Metronidazole", label: "Metronidazole"},
    {value: "Prednisolone", label: "Prednisolone"},
    {value: "Guanfacine", label: "Guanfacine"},
    {value: "Verapamil", label: "Verapamil"},
    {value: "Liraglutide", label: "Liraglutide"},
    {value: "Norethindrone", label: "Norethindrone"},
    {value: "Ropinirole", label: "Ropinirole"},
    {value: "Acetaminophen", label: "Acetaminophen"},
    {value: "Empagliflozin", label: "Empagliflozin"},
    {value: "Hydrocortisone", label: "Hydrocortisone"},
    {value: "Drospirenone; Ethinyl Estradiol", label: "Drospirenone; Ethinyl Estradiol"},
    {value: "Risperidone", label: "Risperidone"},
    {value: "Meclizine", label: "Meclizine"},
    {value: "Albuterol; Ipratropium", label: "Albuterol; Ipratropium"},
    {value: "Adalimumab", label: "Adalimumab"},
    {value: "Nortriptyline", label: "Nortriptyline"},
    {value: "Valsartan", label: "Valsartan"},
    {value: "Cyanocobalamin", label: "Cyanocobalamin"},
    {value: "Etonogestrel; Ethinyl Estradiol", label: "Etonogestrel; Ethinyl Estradiol"},
    {value: "Acyclovir", label: "Acyclovir"},
    {value: "Phentermine", label: "Phentermine"},
    {value: "Cefdinir", label: "Cefdinir"},
    {value: "Timolol", label: "Timolol"},
    {value: "Methylprednisolone", label: "Methylprednisolone"},
    {value: "Oxcarbazepine", label: "Oxcarbazepine"},
    {value: "Morphine", label: "Morphine"},
    {value: "Olmesartan", label: "Olmesartan"},
    {value: "Dicyclomine", label: "Dicyclomine"},
    {value: "Pramipexole", label: "Pramipexole"},
    {value: "Azelastine", label: "Azelastine"},
    {value: "Insulin Degludec", label: "Insulin Degludec"},
    {value: "Memantine", label: "Memantine"},
    {value: "Prazosin", label: "Prazosin"},
    {value: "Ketoconazole", label: "Ketoconazole"},
    {value: "Rizatriptan", label: "Rizatriptan"},
    {value: "Acetaminophen; Codeine", label: "Acetaminophen; Codeine"},
    {value: "Promethazine", label: "Promethazine"},
    {value: "Metformin; Sitagliptin", label: "Metformin; Sitagliptin"},
    {value: "Anastrozole", label: "Anastrozole"},
    {value: "Desvenlafaxine", label: "Desvenlafaxine"},
    {value: "Ramipril", label: "Ramipril"},
    {value: "Pioglitazone", label: "Pioglitazone"},
    {value: "Clobetasol", label: "Clobetasol"},
    {value: "Irbesartan", label: "Irbesartan"},
    {value: "Levofloxacin", label: "Levofloxacin"},
    {value: "Amiodarone", label: "Amiodarone"},
    {value: "Nitroglycerin", label: "Nitroglycerin"},
    {value: "Olanzapine", label: "Olanzapine"},
    {value: "Sucralfate", label: "Sucralfate"},
    {value: "Docusate", label: "Docusate"},
    {value: "Progesterone", label: "Progesterone"},
    {value: "Mirabegron", label: "Mirabegron"},
    {value: "Mupirocin", label: "Mupirocin"},
    {value: "Nebivolol", label: "Nebivolol"},
    {value: "Nitrofurantoin", label: "Nitrofurantoin"},
    {value: "Levocetirizine", label: "Levocetirizine"},
    {value: "Methimazole", label: "Methimazole"},
    {value: "Cyclosporine", label: "Cyclosporine"},
    {value: "Sildenafil", label: "Sildenafil"},
    {value: "Carbamazepine", label: "Carbamazepine"},
    {value: "Labetalol", label: "Labetalol"},
    {value: "Calcium; Cholecalciferol", label: "Calcium; Cholecalciferol"},
    {value: "Lansoprazole", label: "Lansoprazole"},
    {value: "Budesonide", label: "Budesonide"},
    {value: "Colchicine", label: "Colchicine"},
    {value: "Terazosin", label: "Terazosin"},
    {value: "Umeclidinium; Vilanterol", label: "Umeclidinium; Vilanterol"},
    {value: "Lithium", label: "Lithium"},
    {value: "Digoxin", label: "Digoxin"},
    {value: "Dorzolamide; Timolol", label: "Dorzolamide; Timolol"},
    {value: "Melatonin", label: "Melatonin"},
    {value: "Insulin Human; Insulin Isophane Human", label: "Insulin Human; Insulin Isophane Human"},
    {value: "Doxazosin", label: "Doxazosin"},
    {value: "Ranolazine", label: "Ranolazine"},
    {value: "Gemfibrozil", label: "Gemfibrozil"},
    {value: "Amlodipine; Benazepril", label: "Amlodipine; Benazepril"},
    {value: "Temazepam", label: "Temazepam"},
    {value: "Flecainide", label: "Flecainide"},
    {value: "Ticagrelor", label: "Ticagrelor"},
    {value: "Brimonidine", label: "Brimonidine"},
    {value: "Dexlansoprazole", label: "Dexlansoprazole"},
    {value: "Lidocaine", label: "Lidocaine"},
    {value: "Lurasidone", label: "Lurasidone"},
    {value: "Benztropine", label: "Benztropine"},
    {value: "Nystatin", label: "Nystatin"},
    {value: "Eszopiclone", label: "Eszopiclone"},
    {value: "Sacubitril; Valsartan", label: "Sacubitril; Valsartan"},
    {value: "Calcium Citrate", label: "Calcium Citrate"},
    {value: "Sodium", label: "Sodium"},
    {value: "Torsemide", label: "Torsemide"},
    {value: "Butalbital; Acetaminophen; Caffeine", label: "Butalbital; Acetaminophen; Caffeine"},
    {value: "Mesalamine", label: "Mesalamine"},
    {value: "Liothyronine", label: "Liothyronine"},
    {value: "Buprenorphine", label: "Buprenorphine"},
    {value: "Ofloxacin", label: "Ofloxacin"},
    {value: "Erythromycin", label: "Erythromycin"},
    {value: "Doxepin", label: "Doxepin"},
    {value: "Semaglutide", label: "Semaglutide"},
    {value: "Hydromorphone", label: "Hydromorphone"},
    {value: "Penicillin V", label: "Penicillin V"},
    {value: "Valsartan; Hydrochlorothiazide", label: "Valsartan; Hydrochlorothiazide"},
    {value: "Beclomethasone", label: "Beclomethasone"},
    {value: "Brimonidine; Timolol", label: "Brimonidine; Timolol"},
    {value: "Bumetanide", label: "Bumetanide"},
    {value: "Letrozole", label: "Letrozole"},
    {value: "Linagliptin", label: "Linagliptin"},
    {value: "Tretinoin", label: "Tretinoin"},
    {value: "Minocycline", label: "Minocycline"},
    {value: "Ipratropium", label: "Ipratropium"},
    {value: "Polyethylene Glycol 3350", label: "Polyethylene Glycol 3350"},
    {value: "Umeclidinium", label: "Umeclidinium"},
    {value: "Bisoprolol", label: "Bisoprolol"},
    {value: "Calcitriol", label: "Calcitriol"},
    {value: "Varenicline", label: "Varenicline"},
    {value: "Epinephrine", label: "Epinephrine"},
    {value: "Estrogens, Conjugated", label: "Estrogens, Conjugated"},
    {value: "Glyburide", label: "Glyburide"},
    {value: "Guaifenesin", label: "Guaifenesin"},
    {value: "Magnesium Acetate", label: "Magnesium Acetate"},
    {value: "Ethinyl Estradiol; Norgestrel", label: "Ethinyl Estradiol; Norgestrel"},
    {value: "Sotalol", label: "Sotalol"},
    {value: "Bimatoprost", label: "Bimatoprost"},
    {value: "Insulin Isophane", label: "Insulin Isophane"},
    {value: "Medroxyprogesterone", label: "Medroxyprogesterone"},
    {value: "Tamoxifen", label: "Tamoxifen"},
    {value: "Mometasone", label: "Mometasone"},
    {value: "Sulfasalazine", label: "Sulfasalazine"},
    {value: "Dorzolamide", label: "Dorzolamide"},
    {value: "Ketorolac", label: "Ketorolac"},
    {value: "Indomethacin", label: "Indomethacin"},
    {value: "Atomoxetine", label: "Atomoxetine"},
    {value: "Olopatadine", label: "Olopatadine"},
    {value: "Telmisartan", label: "Telmisartan"},
    {value: "Phenytoin", label: "Phenytoin"},
    {value: "Buprenorphine; Naloxone", label: "Buprenorphine; Naloxone"},
    {value: "Raloxifene", label: "Raloxifene"},
    {value: "Tobramycin; Dexamethasone", label: "Tobramycin; Dexamethasone"},
    {value: "Naltrexone", label: "Naltrexone"},
    {value: "Polymyxin B; Trimethoprim", label: "Polymyxin B; Trimethoprim"},
    {value: "Terbinafine", label: "Terbinafine"},
    {value: "Fentanyl", label: "Fentanyl"},
    {value: "Diphenhydramine", label: "Diphenhydramine"},
    {value: "Bisoprolol; Hydrochlorothiazide", label: "Bisoprolol; Hydrochlorothiazide"},
    {value: "Pancrelipase Lipase; Pancrelipase Protease; Pancrelipase Amylase", label: "Pancrelipase Lipase; Pancrelipase Protease; Pancrelipase Amylase"},
    {value: "Zonisamide", label: "Zonisamide"},
    {value: "Fexofenadine", label: "Fexofenadine"},
    {value: "Erenumab", label: "Erenumab"},
    {value: "Linaclotide", label: "Linaclotide"},
    {value: "Brompheniramine; Dextromethorphan; Pseudoephedrine", label: "Brompheniramine; Dextromethorphan; Pseudoephedrine"},
    {value: "Omega-3-acid Ethyl Esters", label: "Omega-3-acid Ethyl Esters"},
    {value: "Dimethyl", label: "Dimethyl"},
    {value: "Tadalafil", label: "Tadalafil"},
    {value: "Canagliflozin", label: "Canagliflozin"},
    {value: "Emtricitabine; Tenofovir Disoproxil", label: "Emtricitabine; Tenofovir Disoproxil"},
    {value: "Tolterodine", label: "Tolterodine"},
    {value: "Etanercept", label: "Etanercept"},
    {value: "Quinapril", label: "Quinapril"},
    {value: "Senna; Docusate", label: "Senna; Docusate"},
    {value: "Betamethasone", label: "Betamethasone"},
    {value: "Solifenacin", label: "Solifenacin"},
    {value: "Insulin, Regular, Human", label: "Insulin, Regular, Human"},
    {value: "Chlorhexidine", label: "Chlorhexidine"},
    {value: "Fluocinonide", label: "Fluocinonide"}]